name: Run WEB Tests
run-name: On Push - Web Tests Run
on: 
  push:
    branches: [ main]
  schedule:
    - cron: '0 5,7,10,13 * * 1,2,3,4,5'

jobs:
    web-test:
        runs-on: ubuntu-20.04
        permissions: write-all
        strategy:
          matrix:
            browser: [chromium, firefox]
          fail-fast: false
        steps:
          - name: Checlout
            uses: actions/checkout@v4

          - name: Install Python 3.10
            uses: actions/setup-python@v4
            with:
              python-version: '3.10'

          - name: Install Node.js 20.10
            uses: actions/setup-node@v3
            with:
              node-version: '20.10'

          - name: Install Requirements
            run: |
              python -m pip install --upgrade pip
              pip install -U -r requirements.txt
              sudo npm install -g npm@10.2.5
              sudo npx playwright install-deps
              rfbrowser init

          - name: Run RTSW WEB Tests
            run: |
              robot -d ./results -v HEADLESS:true -v BROWSER:${{ matrix.browser }} tests

          - name: Upload Tests Results
            if: always()
            uses: actions/upload-artifact@v3
            with:
              name: results-${{ matrix.browser }}
              path: ./results
              if-no-files-found: ignore
              retention-days: 2

          - name: Download Tests Reports
            if: always()
            uses: actions/download-artifact@v1
            with:
              name: results-${{ matrix.browser }}
              
          - name: Send Report
            if: always()
            uses: joonvena/robotframework-reporter-action@v2.1
            with:
              report_path: results-${{ matrix.browser }}
              gh_access_token: ${{ secrets.GITHUB_TOKEN }}
              show_passed_tests: false    
